grub skeleton

diff --git a/unilive-builder b/unilive-builder
--- a/unilive-builder
+++ b/unilive-builder
@@ -1,11 +1,18 @@
 #!/bin/bash
-
 # The following is a native implementation of RemasterSys... simplified actually, for AOSC OS2 Distros.
 # Also it's intended for further *Spin Editions* to be built easily and legitimately.
 
 # What's Implemented Now?
 # 1. A simple interface and routine for mounting build drive and do some clean up.
 # 2. Tells the user what to do with configuration files.
+
+utils-path=${1:-$(dirname $0)}
+
+# ISO Root Check
+if ! [ -d ${utils-path}/example-iso-boot ]; then
+  echo -e "example iso root not found.\nGo to github.com/AOSC-Dev/AOSC-InstallKit to get it."
+  exit 1
+fi
 
 # Prolog...
 echo -e "\033[31mHere is something important before you proceed\033[0m"
@@ -30,7 +37,7 @@ if [ "$(id -u)" != "0" ]; then
    exit 1
 fi
 
-#Get partition
+# Get partition
 echo "Please tell me the partition you've put your distro in: " 
 read partition
 
@@ -68,7 +75,8 @@ fi
 
 # LSB Information Fill-in
 echo -e "Now we need to make sure that you have your /etc/lsb-release file filled in... \033[36m[INFO]\033[0m"
-cp lsb-release lsb-release.change
+lsbinput
+lsbgen > lsb-release.change
 vim lsb-release.change
 mv lsb-release.change /target/etc/lsb-release
 echo -e "/etc/lsb-release filled in... \033[36m[IFNO]\033[0m"
@@ -154,9 +162,9 @@ echo -e "Building squashfs file for the distro... \033[32m[OK]\033[0m"
 
 # Build ISO
 echo -e "You are now required to edit the grub.cfg file for the release... \033[36m[INFO]\033[0m"
-vim /target/iso/boot/grub/grub.cfg
+mkgrubcfg > /target/iso/boot/grub/grub.cfg
 echo -e "Updating GRUB configuration... \033[32m[OK]\033[0m"
-cp -r /example-iso-root /target/
+cp -r /example-iso-boot /target/iso/boot
 mv /target/squash /target/iso/
 grub-mkrescue -o /target/aosc_os2-custom.iso /target/iso
 echo -e "Now building iso for the distro... \033[32m[OK]\033[0m"
@@ -167,7 +175,7 @@ echo -e "Now the iso is ready, be ready to share! \033[36m[HURRAY!!!]\033[0m"
 
 # Function Includes Start
 lsbinput(){
-  . lsb-release || . /etc/lsb-releaae || true
+  . /etc/lsb-releaae || true
   . /etc/os-release || true
   echo "Input the following system infos"
   read -p "Distribution Name/ID of your Distro:" -i ${DISTRIB_ID-AOSC_AnthonOS} DISTRIB_ID
@@ -184,4 +192,18 @@ lsbgen(){
   for i in LSB_VERSION DISTRIB_{ID,RELEASE,CODENAME,DESCRIPTION}; do
     echo "$i=\"${$i}\""
   done
-} 
+}
+# mkgrubcfg > grub.cfg at iso
+mkgrubcfg(){
+  # Skeleton
+  cat grub.cfg | sed "s/\(LANG\)/$LANG/g" | sed "s/\(INITRD\)/$(basename $(ls example-iso-boot/initrd*))/g"
+  menuentry "$DISTRIB_ID, $DISTRIB_RELEASE \"$DISTRIB_CODENAME\"" loadlive quiet rw rootdelay=5
+  menuentry "$DISTRIB_ID, $DISTRIB_RELEASE \"$DISTRIB_CODENAME\" with safe mode graphics" loadlive quiet nomodeset rw rootdelay=5
+}
+
+menuentry(){
+  echo "memuentry \"$1\" {"
+  shift
+  echo -e "  $*"
+  echo "}"
+}
