Function fix.
By the way who the hell added that NICONICONI line?

diff --git a/unilive-builder b/unilive-builder
--- a/unilive-builder
+++ b/unilive-builder
@@ -33,6 +33,77 @@
 # Complete list for not pre-install-able software.
 # Desktop Environment, architecture and PM detection for Target, to get better file name for ISO.
 
+# Functions
+lsbinput() {
+  . /etc/lsb-releaae || true
+  . /etc/os-release || true
+  echo "Input the following system infos:"
+  read -e -p "Distribution Name/ID of your Distro:" -i ${DISTRIB_ID-$ID} DISTRIB_ID
+  read -e -p "Version/Release:" -i ${DISTRIB_RELEASE-$VERSION} DISTRIB_RELEASE
+  read -e -p "Codename:" -i ${DISTRIB_CODENAME-Misaka} DISTRIB_CODENAME
+  read -e -p "Description:" -i ${DISTRIB_DESCRIPTION-$PRETTY_NAME} DISTRIB_DESCRIPTION 
+  lsb_release &> /dev/null && read -p "LSB Version:" -i ${LSB_VERSION-4.1} LSB_VERSION
+}
+
+# lsbgen > lsb-release.change
+lsbgen() {
+  echo "# LSB Release information generated by AOSC unilive-builder"
+  echo "# Source system $NAME, distro timestamp `date -u +%s`($(LANG=C date -u))."
+  # Comment the line if LSB not enabled
+  ! [ $LSB_VERSION ] && printf "# "
+  for i in LSB_VERSION DISTRIB_{ID,RELEASE,CODENAME,DESCRIPTION}; do
+    echo "$i=\"$(eval echo \$$i)\""
+  done
+}
+
+# mkgrubcfg > grub.cfg at iso
+mkgrubcfg() {
+  echo -e "# grub.cfg for Live Medias generated by unilive-builder\n# generate-time: $(LANG=C date -u)/$(date -u +%s)"
+  # Skeleton
+  cat ${lib}/grub.cfg | tail -n +2| sed "s/\(LANG\)/$LANG/g" | sed "s/\(INITRD\)/$(basename $(ls example-iso-boot/initrd*))/g"
+  menuentry "$DISTRIB_ID, $DISTRIB_RELEASE \"$DISTRIB_CODENAME\"" loadlive quiet rw rootdelay=5
+  menuentry "$DISTRIB_ID, $DISTRIB_RELEASE \"$DISTRIB_CODENAME\" with safe mode graphics" loadlive quiet nomodeset rw rootdelay=5
+}
+
+menuentry() {
+  echo "memuentry \"$1\" {"
+  shift
+  echo -e "  $*"
+  echo "}"
+}
+
+do_ok() {
+  printf "$1"
+  (eval "$2" 2>>/tmp/${scriptname-$0}) && echo -e "$3[\e[32mOK\e[0m]" || (
+    echo -e "$3[\e[31mFAILED\e[0m]"
+    read -p "Error occoured. Press any key to continue." -n 1 -t 5 
+    echo "Error information available in /tmp/${scriptname-$0}" && return 1
+  )
+}
+
+ignore_command_not_found() { 
+  local _ret=$?
+  case _ret in
+    127|0)
+      return 0
+      ;;
+    *)
+      return $_ret
+      ;;
+   esac
+}
+
+change_password() {
+  LANG=C expect << EOF
+  spawn chroot /target "passwd $1"
+  expect "Enter new UNIX password:"
+  send "$2\r"
+  expect "Retype new UNIX password:"
+  send "$2\r"
+  expect eof;
+  EOF
+}
+
 lib=${1:-$(dirname $(readlink -e $0))}
 scriptname=unilive-builder
 
@@ -211,76 +282,4 @@ grub-mkrescue -o /target/aosc_os2-custom.iso /target/iso"
 echo -e "Now the iso is ready, be ready to share! \e[36m[HURRAY!!!]\e[0m"
 # echo -e "LIVE CLEAR [\e[36mNICONICONI\e[0m]"
 
-
-# Function Includes Start
-lsbinput() {
-  . /etc/lsb-releaae || true
-  . /etc/os-release || true
-  echo "Input the following system infos:"
-  read -e -p "Distribution Name/ID of your Distro:" -i ${DISTRIB_ID-$ID} DISTRIB_ID
-  read -e -p "Version/Release:" -i ${DISTRIB_RELEASE-$VERSION} DISTRIB_RELEASE
-  read -e -p "Codename:" -i ${DISTRIB_CODENAME-Misaka} DISTRIB_CODENAME
-  read -e -p "Description:" -i ${DISTRIB_DESCRIPTION-$PRETTY_NAME} DISTRIB_DESCRIPTION 
-  lsb_release &> /dev/null && read -p "LSB Version:" -i ${LSB_VERSION-4.1} LSB_VERSION
-}
-
-# lsbgen > lsb-release.change
-lsbgen() {
-  echo "# LSB Release information generated by AOSC unilive-builder"
-  echo "# Source system $NAME, distro timestamp `date -u +%s`($(LANG=C date -u))."
-  # Comment the line if LSB not enabled
-  ! [ $LSB_VERSION ] && printf "# "
-  for i in LSB_VERSION DISTRIB_{ID,RELEASE,CODENAME,DESCRIPTION}; do
-    echo "$i=\"$(eval echo \$$i)\""
-  done
-}
-
-# mkgrubcfg > grub.cfg at iso
-mkgrubcfg() {
-  echo -e "# grub.cfg for Live Medias generated by unilive-builder\n# generate-time: $(LANG=C date -u)/$(date -u +%s)"
-  # Skeleton
-  cat ${lib}/grub.cfg | tail -n +2| sed "s/\(LANG\)/$LANG/g" | sed "s/\(INITRD\)/$(basename $(ls example-iso-boot/initrd*))/g"
-  menuentry "$DISTRIB_ID, $DISTRIB_RELEASE \"$DISTRIB_CODENAME\"" loadlive quiet rw rootdelay=5
-  menuentry "$DISTRIB_ID, $DISTRIB_RELEASE \"$DISTRIB_CODENAME\" with safe mode graphics" loadlive quiet nomodeset rw rootdelay=5
-}
-
-menuentry() {
-  echo "memuentry \"$1\" {"
-  shift
-  echo -e "  $*"
-  echo "}"
-}
-
-do_ok() {
-  printf "$1"
-  (eval "$2" 2>>/tmp/${scriptname-$0}) && echo -e "$3[\e[32mOK\e[0m]" || (
-    echo -e "$3[\e[31mFAILED\e[0m]"
-    read -p "Error occoured. Press any key to continue." -n 1 -t 5 
-    echo "Error information available in /tmp/${scriptname-$0}" && return 1
-  )
-}
-
-ignore_command_not_found() { 
-  local _ret=$?
-  case _ret in
-    127|0)
-      return 0
-      ;;
-    *)
-      return $_ret
-      ;;
-   esac
-}
-
-change_password() {
-  LANG=C expect << EOF
-  spawn chroot /target "passwd $1"
-  expect "Enter new UNIX password:"
-  send "$2\r"
-  expect "Retype new UNIX password:"
-  send "$2\r"
-  expect eof;
-  EOF
-  }
-  
 # -*- vim:fenc=utf-8:shiftwidth=2:softtabstop=2
