。。。

diff --git a/installer-sh/aosc-installer-sh b/installer-sh/aosc-installer-sh
--- a/installer-sh/aosc-installer-sh
+++ b/installer-sh/aosc-installer-sh
@@ -1,19 +1,62 @@
 #!/bin/bash
-install-prepare
+# Enjoy the semi-modular design, use your text editor's find.
+scriptname=$0
+# Prepare
+. /etc/lsb-release
+if !(whiptail --title "$DISTRIB_ID Distribution Installer" --yesno "This installer is designed for CentralPoint and other Community Distributions \nusing bash or virtual terminal as default interface. \n\n\nDo you want to continue?" 15 80)
+then
+  user_abort
+fi 
 
+
+# Staging
+whiptail --title "CentralPoint/Non-GUI Distribution Installer" --msgbox "Here's what we are going to do:\n\n* License Agreement\n* Partition Your Hard Drive\n* Install System\n* Configure and Personalize" --ok-button "Voila!" 20 80
+# While don't agree, ask user to exit or continue.
+while ! (whiptail --title "License Agreement" --yesno "CentralPoint and other distribution from AOSC license under LGPL,\nfor further reading go to:\n\nhttp://www.gnu.org/copyleft/lesser.html\n\nSystem Info:\n\n`lsb_release -a`" --yes-button "Agree" --no-button "No..." 18 80); do
+	if (whiptail --yesno --title "Sorry" --msgbox "We cannot continue the installation unless you agree with the the License Agreement :-(" --yes-button "Quit" --no-button "Continue" 9 50); then user_abort; fi
+done
+
+# Partitioning
+whiptail --title "Partition Your Hard Drive" --msgbox "Here's your partition table so far:\n\n`fdisk -l`" 24 80
+whiptail --title "Partition Your Hard Drive" --yesno "Now we will pop you into GNU Parted...\n\nDo you need to change anything?" 15 65 && parted'
+TARGET=$(whiptail --title "Partition Your Hard Drive" --inputbox "Please tell me the device name of your target partition: " 10 40 3>&1 1>&2 2>&3)
+FS=$(whiptail --title "Partition Your Hard Drive" --menu "Please choose a preferred filesystem from below\n(Currently (df -T | grep $partition | awk '{print $2}' 2>/dev/null; printf "$fs"))" 15 80 6 \
+"ext3" "Third Extended File System" \
+"ext4" "Fourth Extended File System" \
+"jfs" "Journaled File System" \
+"btrfs" "B-tree File System" \
+"xfs" "XFS" 3>&1 1>&2 2>&3)
+whiptail --title "ATTENTION" --yesno "Formatting a partition will cause data lost,\nand _USUALLY_ hard to recover!\n\nAre you =sure that you want to format `cat $TARGET` with `cat $FS`?" 15 65 
+exitstatus=$?
+if [ $exitstatus = 0 ]; then
+        mkfs.$FS $TARGET
+	bash install-install
+else
+        whiptail --title "Error..." --msg
+
+# Libraries
+user_abort(){
+  echo "User aborted install."
+  echo "Run '$scriptname' if you want to start the installer again."
+  exit 0
+}
 # -*- vim:fenc=utf-8:shiftwidth=2:softtabstop=2
 
 # add to vimrc if you want indent.
 # filetype indent on
 # set smartindent
-# autocmd BufRead,BufWritePre *.sh normal gg=G# Automatically merged. For better reading,
+# autocmd BufRead,BufWritePre *.sh normal gg=G
+
+# Automatically merged. For better reading,
 try running gg=G in vim for autoindent after you've set up autoindent.
+
 install-complete() {
 cat /target/etc/bashrc | head -n -1 > /target/etc/bashrc
 whiptail --title "System Installation Complete!" --infobox "Installation has successfully completed,\n your computer will be now restarted" 15 75
 sleep 5
 sync
-reboot}
+reboot 
+}
 install-configure() {
 BOOT=/tmp/boot_dev
 ESP=/tmp/esp
@@ -72,70 +115,10 @@ whiptail --title "Installation Stage" --msgbox "We are now ready to install `lsb
 mkdir /target
 mount `cat $TARGET` /target
 install-copy
+}
 
-}
-install-partition() {
-export TARGET=/tmp/target_disk
-export FS=/tmp/target_fs
 
-whiptail --title "Partition Your Hard Drive" --msgbox "Here's your partition table so far:\n\n`fdisk -l`" 24 80
-whiptail --title "Partition Your Hard Drive" --yesno "Now we will pop you into GNU Parted to do some partitioning...\n\nDo you need to change anything?" 15 65
-exitstatus=$?
-if [ $exitstatus = 0 ]; then
-	parted
-else
-	true
-fi
-whiptail --title "Partition Your Hard Drive" --inputbox "Please tell me the device name of your target partition: " 10 40 \
-2> "$TARGET"
-whiptail --title "Partition Your Hard Drive" --menu "Please choose a preferred filesystem from below" 15 80 6 \
-"ext3" "Third Extended File System" \
-"ext4" "Fourth Extended File System" \
-"jfs" "Journaled File System" \
-"btrfs" "B-tree File System" \
-"xfs" "XFS" 2> $FS
-whiptail --title "ATTENTION" --yesno "Formatting a partition will cause data lost,\nand _USUALLY_ hard to recover!\n\nAre you sure that you want to format `cat $TARGET` with `cat $FS`?" 15 65 
-exitstatus=$?
-if [ $exitstatus = 0 ]; then
-        mkfs.`cat $FS` `cat $TARGET`
-	bash install-install
-else
-        whiptail --title "Error..." --msgbox "In early stage development, we don't support\ninstalling without formating the target partition.\n\nWe apologize for the inconvenience."  12 65
-	exit 1
-fi
-}
-install-prepare() {
-whiptail --title "CentralPoint/Non-GUI Distribution Installer" --yesno "This installer is designed for CentralPoint or other Community Distribution \nusing bash or virtual terminal as default interface. \n\n\nDo you want to continue?" 15 80
-exitstatus=$?
-if [ $exitstatus = 0 ]
-then
-	install-staging
-else
-	whiptail --title "Huh?" --yesno "Are you sure that you want to quit?" 8 40
-	exitstatus=$?
-	if [ $exitstatus = 0 ]
-	then
-		exit 0
-		echo "(Exit status was $exitstatus)"
-	else
-		install-prepare
-		echo "(Exit status was $exitstatus)"
-	fi
-fi 
-echo "(Exit status was $exitstatus)"
 
-}
-install-staging() {
-whiptail --title "CentralPoint/Non-GUI Distribution Installer" --msgbox "Here's what we are going to do:\n\n* License Agreement\n* Partition Your Hard Drive\n* Install System\n* Configure and Personalize\n* Voila!" 20 80
-whiptail --title "License Agreement" --yesno "CentralPoint and other distribution from AOSC license under LGPL,\nfor further reading go to:\n\nhttp://www.gnu.org/copyleft/lesser.html\n\nSystem Info:\n\n`lsb_release -a`\n\nDo you agree and still want to continue?" 20 80
-exitstatus=$?
-if [ $exitstatus = 0 ]; then
-	install-partition
-else
-	whiptail --title "Sorry" --msgbox "We cannot continue the installation unless you agree with the the License Agreement :-(" 8 50
-	exit 0
-fi
-}
 install-user() {
 USERNAME=/tmp/username
 PASSWD=/tmp/passwd
